// src/utils/exportData.js
import jsPDF from 'jspdf';
import 'jspdf-autotable';

/**
 * Export activities to CSV
 * @param {Array} activities - Array of activity objects
 * @param {string} filename - Output filename
 */
export const exportToCSV = (activities, filename = 'activities.csv') => {
  if (!activities || activities.length === 0) {
    throw new Error('No activities to export');
  }

  // CSV Headers
  const headers = ['Date', 'Type', 'Distance (km)', 'Duration (min)', 'Calories', 'Pace (min/km)'];
  
  // Convert activities to CSV rows
  const rows = activities.map(activity => {
    const pace = activity.distance_km > 0 
      ? (activity.duration_min / activity.distance_km).toFixed(2)
      : '-';
    
    return [
      new Date(activity.date).toLocaleDateString(),
      activity.type,
      activity.distance_km,
      activity.duration_min,
      activity.calories_burned || '-',
      pace
    ];
  });

  // Build CSV content
  const csvContent = [
    headers.join(','),
    ...rows.map(row => row.join(','))
  ].join('\n');

  // Create blob and download
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  const url = URL.createObjectURL(blob);
  
  link.setAttribute('href', url);
  link.setAttribute('download', filename);
  link.style.visibility = 'hidden';
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

/**
 * Export activities to PDF
 * @param {Array} activities - Array of activity objects
 * @param {Object} user - User object
 * @param {Object} stats - User statistics
 * @param {string} filename - Output filename
 */
export const exportToPDF = (activities, user, stats = {}, filename = 'activities-report.pdf') => {
  const doc = new jsPDF();
  
  // Title
  doc.setFontSize(20);
  doc.setTextColor(46, 125, 50); // brand.500
  doc.text('The Trek - Activity Report', 14, 22);
  
  // User info
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  doc.text(`Generated for: ${user.username || 'User'}`, 14, 32);
  doc.text(`Report Date: ${new Date().toLocaleDateString()}`, 14, 38);
  
  // Summary statistics
  if (stats) {
    doc.setFontSize(14);
    doc.setTextColor(46, 125, 50);
    doc.text('Summary Statistics', 14, 50);
    
    doc.setFontSize(10);
    doc.setTextColor(0, 0, 0);
    let yPos = 58;
    
    if (stats.total_activities) {
      doc.text(`Total Activities: ${stats.total_activities}`, 14, yPos);
      yPos += 6;
    }
    if (stats.total_distance) {
      doc.text(`Total Distance: ${stats.total_distance.toFixed(2)} km`, 14, yPos);
      yPos += 6;
    }
    if (stats.total_duration) {
      doc.text(`Total Duration: ${stats.total_duration} minutes`, 14, yPos);
      yPos += 6;
    }
    if (stats.total_calories) {
      doc.text(`Total Calories: ${stats.total_calories} kcal`, 14, yPos);
      yPos += 6;
    }
    if (stats.avg_distance) {
      doc.text(`Average Distance: ${stats.avg_distance.toFixed(2)} km`, 14, yPos);
      yPos += 6;
    }
    
    yPos += 4;
  }
  
  // Activities table
  const tableStartY = stats ? 95 : 48;
  doc.setFontSize(14);
  doc.setTextColor(46, 125, 50);
  doc.text('Activities', 14, tableStartY);
  
  const tableData = activities.map(activity => {
    const pace = activity.distance_km > 0
      ? (activity.duration_min / activity.distance_km).toFixed(2)
      : '-';
    
    return [
      new Date(activity.date).toLocaleDateString(),
      activity.type,
      activity.distance_km,
      activity.duration_min,
      activity.calories_burned || '-',
      pace
    ];
  });
  
  doc.autoTable({
    startY: tableStartY + 5,
    head: [['Date', 'Type', 'Distance\n(km)', 'Duration\n(min)', 'Calories', 'Pace\n(min/km)']],
    body: tableData,
    theme: 'grid',
    headStyles: {
      fillColor: [46, 125, 50], // brand.500
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      halign: 'center'
    },
    styles: {
      fontSize: 9,
      cellPadding: 3,
      overflow: 'linebreak',
      halign: 'center'
    },
    columnStyles: {
      0: { cellWidth: 30 },
      1: { cellWidth: 25 },
      2: { cellWidth: 22 },
      3: { cellWidth: 22 },
      4: { cellWidth: 22 },
      5: { cellWidth: 22 }
    },
    margin: { top: 10 },
  });
  
  // Footer
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128);
    doc.text(
      `Page ${i} of ${pageCount} | Generated by The Trek - trekfit.co.ke`,
      doc.internal.pageSize.getWidth() / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    );
  }
  
  // Save PDF
  doc.save(filename);
};

/**
 * Calculate summary statistics from activities
 * @param {Array} activities - Array of activity objects
 * @returns {Object} - Summary statistics
 */
export const calculateStats = (activities) => {
  if (!activities || activities.length === 0) {
    return null;
  }
  
  const stats = activities.reduce((acc, activity) => {
    acc.total_distance += activity.distance_km || 0;
    acc.total_duration += activity.duration_min || 0;
    acc.total_calories += activity.calories_burned || 0;
    acc.total_activities += 1;
    return acc;
  }, {
    total_activities: 0,
    total_distance: 0,
    total_duration: 0,
    total_calories: 0
  });
  
  stats.avg_distance = stats.total_activities > 0
    ? stats.total_distance / stats.total_activities
    : 0;
  
  stats.avg_duration = stats.total_activities > 0
    ? stats.total_duration / stats.total_activities
    : 0;
  
  return stats;
};
